### PR TITLE
Namespaced

### PR DESCRIPTION
**Pull request by toooni**
- resolved the merge conflicts of the PR of @ericpruitt
- changed CannedResponses and Tickets to use namespaces too
- updated/fixed tests

### CODE REVIEW

**Comment by ericpruitt** [comment]
User beware: I am pretty sure I discovered a bug in that pull request at
some point, and although I fixed the bug in the copy of the LiveChat API
used by my employer, I never bothered to update the pull request because
it didn't seem like anyone cared. Unfortunately, I can't remember the
nature of the problem anymore.

Eric

**Comment by bolchowka** [comment]
Hi guys,
thanks for commiting to our PHP client code. We will have a look at that soon and consider merging your changes to master branch. We'll keep you posted.

**Comment by toooni** [comment]
@ericpruitt thank you.. i'll look into it. i had found some bugs and fixed them (all get actions seemed to work pretty fine..) i will check some put actions today too..
@bolchowka thank you.. i'll write as soon as i have double checked everything..

**Comment by toooni** [comment]
@bolchowka fixed issue on agents (only accepting integer id's but login needed).

**Comment by toooni** [comment]
@bolchowka haven't tested every function because i don't want to mess with our chat system. But I am pretty sure that everything is working better than before.

**Comment by HaGii** [comment]
@toooni thanks for commiting. I added support for namespaces and merged it to [1.0 branch](https://github.com/livechat/api-client-php/tree/1.0). List of other changes: Pull request #11.

**Comment by HaGii** [comment]
@toooni thanks for commiting. I added support for namespaces and merged it to [1.0 branch](https://github.com/livechat/api-client-php/tree/1.0). List of other changes: Pull request #11.

**Pull request closed without merging**
